import { z } from "zod";
import {
  LastOutcomeSchema,
  nullableNumber,
  nullableString,
} from "./common";

export const AutoresearchStatusSchema = z.object({
  schema: z.string().optional(),
  state: z.enum(["idle", "running", "stopping", "crashed"]).catch("idle"),
  pid: nullableNumber,
  request_id: nullableString,
  iteration: z.coerce.number().catch(0),
  max: z.coerce.number().catch(0),
  last_step: nullableString,
  last_eval: nullableString,
  route_status: nullableString,
  heartbeat_age_s: nullableNumber,
  heartbeat_fresh: z.boolean().catch(false),
  last_receipt: nullableString,
  last_run: z.unknown().nullable().catch(null),
  note: nullableString,
});

export const AutoresearchRunSchema = z.object({
  at: z.string().catch(""),
  lane: z.enum(["skill", "code", "deep-audit", "test"]).catch("skill"),
  request_id: z.string().nullable().catch(null),
  tokens: z.coerce.number().catch(0),
  proposed: z.coerce.number().catch(0),
  errors: z.coerce.number().catch(0),
  vetoed: z.coerce.number().catch(0).optional(),
  scanned: z.coerce.number().catch(0),
  model: z.string().nullable().catch(null).optional(),
});

export const AutoresearchRunsResponseSchema = z.object({
  schema: z.string().optional(),
  runs: z.array(AutoresearchRunSchema).catch([]),
});

export const ProposalSchema = z.object({
  id: z.string(),
  target: z.string().catch(""),
  section: z.string().nullable().catch(null),
  title: z.string().nullable().optional(),
  category: z.string().nullable().catch(null).optional(),
  severity: z.enum(["critical", "high", "medium", "low"]).nullable().catch(null).optional(),
  evidence: z.string().nullable().catch(null).optional(),
  new_text: z.string().nullable().optional(),
  proposal_type: z.string().nullable().catch(null).optional(),
  rationale_plain: z.string().catch(""),
  diff_before_after: z.string().catch(""),
  rank_score: z.coerce.number().nullable().catch(null).optional(),
  mode: z.enum(["skill", "code", "test"]).catch("skill"),
  // Unknown lifecycle values must fail closed into history, never inflate the
  // operator inbox as `proposed`.
  status: z.enum(["proposed", "testing", "applied", "skipped", "routed_to_kanban", "pooled", "escalated"]).catch("skipped"),
  last_outcome: LastOutcomeSchema.optional(),
  result: z.string().nullable().optional(),
  created_at: z.union([z.number(), z.string()]).nullable().optional(),
  applied_at: z.union([z.number(), z.string()]).nullable().optional(),
  gate: z.object({
    phase: z.enum(["running", "passed", "failed", "crashed"]).catch("running"),
    started_at: nullableString.optional(),
    finished_at: nullableString.optional(),
    returncode: nullableNumber.optional(),
    summary: nullableString.optional(),
  }).nullable().optional(),
  finding_state: z.enum(["detected", "verified", "rejected", "stale"]).optional(),
  decision_state: z.enum(["needs_operator", "accepted", "dismissed"]).optional(),
  delivery_state: z.enum(["none", "queued", "running", "review", "integrated", "failed"]).optional(),
  operator_action_required: z.boolean().optional(),
  decision_owner: nullableString.optional(),
  disposition_reason: nullableString.optional(),
  disposition_source: nullableString.optional(),
  duplicate_of: nullableString.optional(),
  finding_fingerprint: nullableString.optional(),
  target_sha256: nullableString.optional(),
  target_current_sha256: nullableString.optional(),
  target_stale: z.boolean().catch(false).optional(),
  kanban_task_id: nullableString.optional(),
  escalation_task_id: nullableString.optional(),
  linked_task_id: nullableString.optional(),
  linked_task_title: nullableString.optional(),
  linked_task_status: nullableString.optional(),
  test_code: nullableString.optional(),
  caught_mutant: z.record(z.string(), z.unknown()).nullable().optional(),
  affected_tests: z.array(z.string()).catch([]).optional(),
  expected_benefit: nullableString.optional(),
  risk_summary: nullableString.optional(),
  test_plan: nullableString.optional(),
  recommendation: nullableString.optional(),
  outcome_schema_version: z.coerce.number().optional(),
  outcome_applicability: z.enum(["applicable", "not_applicable"]).optional(),
  measurement_status: z.enum(["not_started", "pending", "measuring", "measured", "retryable_failure", "exhausted"]).optional(),
  outcome_verdict: z.enum(["improved", "neutral", "worsened", "unmeasurable", "confounded"]).nullable().optional(),
  evidence_grade: z.enum(["legacy_observational", "contract_verified"]).optional(),
  calibration_eligible: z.boolean().optional(),
  outcome_class: nullableString.optional(),
  outcome_authority: nullableString.optional(),
  probe_contract: z.object({
    schema_version: z.coerce.number().optional(),
    outcome_contract_version: z.coerce.number().optional(),
    contract_id: z.string().optional(),
    contract_hash: z.string().optional(),
    contract_sha256: z.string().optional(),
    claim: z.string().optional(),
    measurement_kind: z.enum(["invariant", "metric_delta", "runtime_observation"]).optional(),
    probe_id: z.string().optional(),
    probe_args: z.record(z.string(), z.unknown()).optional(),
    success_template_id: z.string().optional(),
    success_parameters: z.record(z.string(), z.unknown()).optional(),
    success_rule: z.record(z.string(), z.unknown()).optional(),
    outcome_class: z.string().optional(),
    counter_probes: z.array(z.record(z.string(), z.unknown())).optional(),
    counter_rules: z.array(z.record(z.string(), z.unknown())).optional(),
    sampling_plan: z.record(z.string(), z.unknown()).optional(),
    observation_window: z.record(z.string(), z.unknown()).optional(),
    trigger: z.enum(["integrated_commit", "deployed_runtime"]).optional(),
    measurement_budget: z.record(z.string(), z.unknown()).optional(),
    environment_requirements: z.record(z.string(), z.unknown()).optional(),
    calibration_eligible: z.boolean().optional(),
    args: z.record(z.string(), z.unknown()).optional(),
    comparator: z.record(z.string(), z.unknown()).optional(),
    sampling: z.record(z.string(), z.unknown()).optional(),
    budget: z.record(z.string(), z.unknown()).optional(),
    requires_delivery_sha: z.boolean().optional(),
    baseline_recorded_at: z.coerce.number().optional(),
    release_fingerprint: z.string().optional(),
  }).nullable().optional(),
  outcome_baseline: z.record(z.string(), z.unknown()).nullable().optional(),
  outcome_measured_at: z.coerce.number().nullable().optional(),
  outcome_observation: z.record(z.string(), z.unknown()).nullable().optional(),
  outcome_cost_usd: z.coerce.number().nullable().optional(),
  outcome_cost_actual_usd: z.coerce.number().nullable().optional(),
  outcome_cost_api_equivalent_usd: z.coerce.number().nullable().optional(),
  outcome_cost_effective_usd: z.coerce.number().nullable().optional(),
  outcome_cost_status: z.enum(["complete", "partial", "unknown"]).nullable().optional(),
  outcome_cost_breakdown: z.record(z.string(), z.coerce.number()).nullable().optional(),
  outcome_unknown_cost_refs: z.array(z.string()).nullable().optional(),
  outcome_operator_interventions: z.coerce.number().nullable().optional(),
  outcome_integration_sha: nullableString.optional(),
});

export const ProposalsResponseSchema = z.object({
  schema: z.string().optional(),
  count: z.coerce.number().catch(0),
  open_count: z.coerce.number().catch(0),
  reverted_count: z.coerce.number().catch(0),
  testing_count: z.coerce.number().catch(0),
  applied_count: z.coerce.number().catch(0),
  skipped_count: z.coerce.number().catch(0),
  delivery_count: z.coerce.number().catch(0),
  integrated_count: z.coerce.number().catch(0),
  stale_count: z.coerce.number().catch(0),
  dismissed_count: z.coerce.number().catch(0),
  metrics: z.object({
    operator_decisions: z.coerce.number().catch(0),
    accepted: z.coerce.number().catch(0),
    dismissed: z.coerce.number().catch(0),
    precision: z.coerce.number().nullable().catch(null),
    code_precision: z.coerce.number().nullable().catch(null),
    stale_rate: z.coerce.number().catch(0),
    duplicate_rate: z.coerce.number().catch(0),
    cost_per_accepted_usd: z.coerce.number().nullable().catch(null),
    outcomes: z.object({
      applicable: z.coerce.number().catch(0),
      not_applicable: z.coerce.number().catch(0),
      pending: z.coerce.number().catch(0),
      measured: z.coerce.number().catch(0),
      verified_measured: z.coerce.number().catch(0),
      measurement_coverage: z.coerce.number().catch(0),
      outcome_coverage: z.coerce.number().catch(0),
      directional_coverage: z.coerce.number().catch(0),
      verified_directional_denominator: z.coerce.number().catch(0),
      verified_benefit_rate: z.coerce.number().nullable().catch(null),
      regression_rate: z.coerce.number().nullable().catch(null),
      unmeasurable_rate: z.coerce.number().nullable().catch(null),
      verified_improved: z.coerce.number().catch(0),
      legacy_improved: z.coerce.number().catch(0),
      improved: z.coerce.number().catch(0),
      neutral: z.coerce.number().catch(0),
      worsened: z.coerce.number().catch(0),
      unmeasurable: z.coerce.number().catch(0),
      confounded: z.coerce.number().catch(0),
      measurement_cost_usd: z.coerce.number().nullable().catch(null),
      known_measurement_cost_usd: z.coerce.number().catch(0),
      measurement_actual_cost_usd: z.coerce.number().nullable().optional(),
      measurement_api_equivalent_cost_usd: z.coerce.number().nullable().optional(),
      measurement_effective_cost_usd: z.coerce.number().nullable().optional(),
      known_measurement_actual_cost_usd: z.coerce.number().optional(),
      known_measurement_api_equivalent_cost_usd: z.coerce.number().optional(),
      known_measurement_effective_cost_usd: z.coerce.number().optional(),
      cost_complete_outcomes: z.coerce.number().catch(0),
      unknown_cost_outcomes: z.coerce.number().catch(0),
      cost_coverage: z.coerce.number().catch(0),
      cost_per_measured_usd: z.coerce.number().nullable().catch(null),
      cost_per_improved_usd: z.coerce.number().nullable().catch(null),
      cost_per_verified_benefit_usd: z.coerce.number().nullable().catch(null),
      actual_cost_per_verified_benefit_usd: z.coerce.number().nullable().optional(),
      api_equivalent_cost_per_verified_benefit_usd: z.coerce.number().nullable().optional(),
      effective_cost_per_verified_benefit_usd: z.coerce.number().nullable().optional(),
      operator_interventions: z.coerce.number().catch(0),
      operator_interventions_per_verified_benefit: z.coerce.number().nullable().catch(null),
    }).optional(),
  }).optional(),
  proposals: z.array(ProposalSchema).catch([]),
});
