/**
 * Real live-payload fixture for chainList.test.ts — a trimmed slice of the
 * actual GET /api/plugins/kanban/board response (BoardResponseSchema shape),
 * captured 2026-07-02 from the running hermes-dashboard.service on
 * 127.0.0.1:9119 via:
 *
 *   POST /auth/password-login {provider:"basic", username, password}
 *   GET  /api/plugins/kanban/board?card_diagnostics=summary&card_body=none
 *
 * Contains, unmodified from the live response:
 *  - a real named 2-member DONE chain (t_3731875b)
 *  - a real UNNAMED (root missing) 2-member DONE chain (t_5fb20eb6, the
 *    "FO-0134 …/kitchen …" pair)
 *  - a real UNNAMED (root missing) 1-member DONE chain (t_0e5ca6d6 — the
 *    exact zombie id the S1 ticket flagged as showing a bare id in the old
 *    dropdown; its only member t_34b0a94e has a real title)
 *
 * The live snapshot at capture time had ZERO non-done chains (board columns:
 * running=0, todo/scheduled/ready=0, the only 2 blocked tasks were self-root
 * singles outside the Ketten grouping) — nothing to source a "running"/
 * "waiting" MULTI-MEMBER chain example from. To still exercise those groups
 * against a real chain shape, exactly two `status` fields (+ their
 * `completed_at`, nulled for consistency) were flipped to a different real,
 * schema-valid status on an otherwise-untouched real chain:
 *  - t_d3eb22f2 (root of a real 2-member done chain) done → running
 *  - t_0deb6946 (non-root member of a different real 2-member done chain)
 *    done → blocked
 * Every other field on every task is byte-identical to the live response.
 */
export const chainListBoardFixture: unknown = {
  "columns": [
    {
      "name": "running",
      "tasks": [
        {
          "id": "t_d3eb22f2",
          "title": "Upstream Sync 2026-06-22 Slice 1 — Gateway approval-prompt credential redaction",
          "assignee": "coder",
          "status": "running",
          "priority": 100,
          "created_by": "default-orchestrator",
          "created_at": 1782131291,
          "started_at": 1782135175,
          "completed_at": null,
          "workspace_kind": "worktree",
          "workspace_path": "/home/piet/.hermes/hermes-agent/.worktrees/kanban/t_6661c5cc",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": "project_hermes_upstream_sync_2026_06_22",
          "branch_name": "kanban/t_6661c5cc",
          "idempotency_key": "project_hermes_upstream_sync_2026_06_22:security-redaction",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": 2700,
          "last_heartbeat_at": 1782135726,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": 1,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": "code",
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 881034,
            "started_age_seconds": 877150,
            "time_to_complete_seconds": 604
          },
          "latest_summary": "{\"action\":\"uphold\",\"workflow_id\":null,\"reason\":\"C-1..C-5 pass: scoped upstream slice verified; required gate and diff-check pass; no unredacted approval egress found.\",\"missing\":[]}",
          "block_reason": null,
          "link_counts": {
            "parents": 1,
            "children": 0
          },
          "comment_count": 4,
          "progress": null,
          "root_id": "t_d3eb22f2",
          "vault_memory_links": [],
          "cost_usd": 0.0,
          "input_tokens": 224808,
          "output_tokens": 19021,
          "cost_usd_equivalent": 0.795011692,
          "cost_effective_usd": 0.795011692
        }
      ]
    },
    {
      "name": "blocked",
      "tasks": [
        {
          "id": "t_0deb6946",
          "title": "Scout: Review/Einsteuerung PlanSpec A: Worker Review Lifecycle Contract",
          "assignee": "scout",
          "status": "blocked",
          "priority": 100,
          "created_by": "auto-scout-critical",
          "created_at": 1782508076,
          "started_at": 1782508132,
          "completed_at": null,
          "workspace_kind": "scratch",
          "workspace_path": "/home/piet/.hermes/kanban/workspaces/t_0deb6946",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": null,
          "branch_name": null,
          "idempotency_key": "auto-scout:t_3731875b",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": 1800,
          "last_heartbeat_at": 1782508565,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": null,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": null,
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 504249,
            "started_age_seconds": 504193,
            "time_to_complete_seconds": 443
          },
          "latest_summary": "Reviewed the review-lifecycle contract slice and found it consistent with the intended producer/verifier flow. The code paths for `complete_task(review_gate=True)`, `claim_review_task`, and the `revie",
          "block_reason": null,
          "link_counts": {
            "parents": 0,
            "children": 1
          },
          "comment_count": 1,
          "progress": {
            "done": 1,
            "total": 1
          },
          "root_id": "t_3731875b",
          "vault_memory_links": [
            {
              "kind": "vault",
              "label": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "target": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "source": "body",
              "path": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "display_path": "03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "exists": false,
              "obsidian_url": "obsidian://open?path=%2Fhome%2Fpiet%2Fvault%2F03-Agents%2FHermes%2Freceipts%2F2026-06-26-worker-review-lifecycle-contract-local-implementation.md%60",
              "url": null
            }
          ],
          "cost_usd": 0.0,
          "input_tokens": 600513,
          "output_tokens": 14937,
          "cost_usd_equivalent": 0.69523965,
          "cost_effective_usd": 0.69523965
        }
      ]
    },
    {
      "name": "done",
      "tasks": [
        {
          "id": "t_6661c5cc",
          "title": "Scout: Upstream Sync 2026-06-22 Slice 1 — Gateway approval-prompt credential redaction",
          "assignee": "scout",
          "status": "done",
          "priority": 100,
          "created_by": "auto-scout-critical",
          "created_at": 1782131291,
          "started_at": 1782131313,
          "completed_at": 1782131626,
          "workspace_kind": "scratch",
          "workspace_path": "/home/piet/.hermes/kanban/workspaces/t_6661c5cc",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": "project_hermes_upstream_sync_2026_06_22",
          "branch_name": null,
          "idempotency_key": "auto-scout:t_d3eb22f2",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": 1800,
          "last_heartbeat_at": 1782131621,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": null,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": null,
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 881034,
            "started_age_seconds": 881012,
            "time_to_complete_seconds": 313
          },
          "latest_summary": "Scoped the gateway approval-prompt redaction seam. The likely fix sits in `acp_adapter/permissions.py` where raw command/description are forwarded into ACP tool-call payloads; `agent/redact.py` alread",
          "block_reason": null,
          "link_counts": {
            "parents": 0,
            "children": 1
          },
          "comment_count": 1,
          "progress": {
            "done": 1,
            "total": 1
          },
          "root_id": "t_d3eb22f2",
          "vault_memory_links": [],
          "cost_usd": 0.0,
          "input_tokens": 567511,
          "output_tokens": 10416,
          "cost_usd_equivalent": 0.47250525,
          "cost_effective_usd": 0.47250525
        },
        {
          "id": "t_3731875b",
          "title": "Review/Einsteuerung PlanSpec A: Worker Review Lifecycle Contract",
          "assignee": "reviewer",
          "status": "done",
          "priority": 100,
          "created_by": "user",
          "created_at": 1782508075,
          "started_at": 1782508616,
          "completed_at": 1782508864,
          "workspace_kind": "scratch",
          "workspace_path": "/home/piet/.hermes/kanban/workspaces/t_3731875b",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": null,
          "branch_name": null,
          "idempotency_key": "2026-06-26-planspec-a-worker-review-lifecycle-review",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": null,
          "last_heartbeat_at": 1782508798,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": null,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": "e_5d466b79",
          "kind": "review",
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 504250,
            "started_age_seconds": 503709,
            "time_to_complete_seconds": 248
          },
          "latest_summary": "APPROVED — A-Slice review-lifecycle-contract (0d5f5d397) sicher integrierbar; Daten-Layer-Guard korrekt+grün (64 passed), 1 bounded Tool-Layer-Follow-up",
          "block_reason": null,
          "link_counts": {
            "parents": 1,
            "children": 0
          },
          "comment_count": 1,
          "progress": null,
          "root_id": "t_3731875b",
          "vault_memory_links": [
            {
              "kind": "vault",
              "label": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "target": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "source": "body",
              "path": "/home/piet/vault/03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "display_path": "03-Agents/Hermes/receipts/2026-06-26-worker-review-lifecycle-contract-local-implementation.md`",
              "exists": false,
              "obsidian_url": "obsidian://open?path=%2Fhome%2Fpiet%2Fvault%2F03-Agents%2FHermes%2Freceipts%2F2026-06-26-worker-review-lifecycle-contract-local-implementation.md%60",
              "url": null
            }
          ],
          "cost_usd": 0.0,
          "input_tokens": 89083,
          "output_tokens": 16161,
          "cost_usd_equivalent": 2.0694395,
          "cost_effective_usd": 2.0694395
        },
        {
          "id": "t_34b0a94e",
          "title": "Agent-Terminals: Gates reparieren und Handoff-PlanSpec einreichen (Build plus Test)",
          "assignee": "premium",
          "status": "done",
          "priority": 0,
          "created_by": "strategist-cron",
          "created_at": 1782790369,
          "started_at": 1782801968,
          "completed_at": 1782803350,
          "workspace_kind": "dir",
          "workspace_path": "/home/piet/.hermes/hermes-agent/.worktrees/kanban/t_0e5ca6d6",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": "planspec",
          "branch_name": "kanban/t_0e5ca6d6",
          "idempotency_key": null,
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": null,
          "last_heartbeat_at": 1782803298,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": null,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": "code",
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 221957,
            "started_age_seconds": 210358,
            "time_to_complete_seconds": 1382
          },
          "latest_summary": "Critic UPHOLD: 5/5 Checks grün — AC-1/2/3 dreifach geerdet (verifier-Run 5921 + eigene Quell-/Artifact-/validate-Prüfung), 2 Disp. verifiziert-erledigt nicht doppelt gebaut, 2 sauber in held PlanSpec ",
          "block_reason": null,
          "link_counts": {
            "parents": 0,
            "children": 2
          },
          "comment_count": 2,
          "progress": {
            "done": 0,
            "total": 2
          },
          "root_id": "t_0e5ca6d6",
          "vault_memory_links": [],
          "cost_usd": 0.0,
          "input_tokens": 352497,
          "output_tokens": 107429,
          "cost_usd_equivalent": 8.0279181,
          "cost_effective_usd": 8.0279181
        },
        {
          "id": "t_15a10457",
          "title": "FO-0134 Coder retry: Reverify/Repair /kitchen Termin-Schnellerfassung",
          "assignee": "coder",
          "status": "done",
          "priority": 205,
          "created_by": "default",
          "created_at": 1780925760,
          "started_at": 1780925769,
          "completed_at": 1780926594,
          "workspace_kind": "dir",
          "workspace_path": "/home/piet/projects/family-organizer",
          "claim_lock": null,
          "claim_expires": null,
          "tenant": "family-organizer-0134",
          "branch_name": null,
          "idempotency_key": "fo-0134-native-coder-retry-noskill-20260608",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": 7200,
          "last_heartbeat_at": 1780926396,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": 2,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": true,
          "goal_max_turns": 20,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": null,
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 2086565,
            "started_age_seconds": 2086556,
            "time_to_complete_seconds": 825
          },
          "latest_summary": "review-required handoff terminalized by Orchestrator so dependent reviewer can run; review must audit coder comment and residual Playwright-browser risk.",
          "block_reason": null,
          "link_counts": {
            "parents": 1,
            "children": 2
          },
          "comment_count": 1,
          "progress": {
            "done": 1,
            "total": 2
          },
          "root_id": "t_5fb20eb6",
          "vault_memory_links": [],
          "cost_usd": 0.0,
          "input_tokens": 280156,
          "output_tokens": 12502,
          "cost_usd_equivalent": 4.255712,
          "cost_effective_usd": 4.255712
        },
        {
          "id": "t_2a6663ba",
          "title": "FO-0134 native Kanban: /kitchen Termin-Schnellerfassung Reverify/Repair",
          "assignee": null,
          "status": "done",
          "priority": 200,
          "created_by": "default",
          "created_at": 1780925533,
          "started_at": null,
          "completed_at": 1780925534,
          "workspace_kind": "scratch",
          "workspace_path": null,
          "claim_lock": null,
          "claim_expires": null,
          "tenant": "family-organizer-0134",
          "branch_name": null,
          "idempotency_key": "fo-0134-native-root-20260608",
          "consecutive_failures": 0,
          "worker_pid": null,
          "last_failure_error": null,
          "max_runtime_seconds": null,
          "last_heartbeat_at": null,
          "current_run_id": null,
          "workflow_template_id": null,
          "current_step_key": null,
          "skills": null,
          "model_override": null,
          "review_tier": null,
          "max_retries": null,
          "max_iterations": null,
          "continuation_count": 0,
          "max_continuations": null,
          "last_continuation_reason": null,
          "budget_extension_count": 0,
          "budget_progress_marker": null,
          "goal_mode": false,
          "goal_max_turns": null,
          "session_id": null,
          "due_at": null,
          "epic_id": null,
          "kind": null,
          "scope_contract": null,
          "auto_retry_count": 0,
          "integration_retry_count": 0,
          "transient_retry_count": 0,
          "age": {
            "created_age_seconds": 2086792,
            "started_age_seconds": null,
            "time_to_complete_seconds": 1
          },
          "latest_summary": "Root spec accepted; run coder child then verdict-only reviewer.",
          "block_reason": null,
          "link_counts": {
            "parents": 0,
            "children": 2
          },
          "comment_count": 1,
          "progress": {
            "done": 1,
            "total": 2
          },
          "root_id": "t_5fb20eb6",
          "vault_memory_links": [],
          "cost_usd": 0.0,
          "input_tokens": 0,
          "output_tokens": 0,
          "cost_usd_equivalent": 0.0,
          "cost_effective_usd": 0.0
        }
      ]
    }
  ],
  "tenants": [
    "family-organizer-0134",
    "planspec",
    "project_hermes_upstream_sync_2026_06_22"
  ],
  "assignees": [
    "coder",
    "premium",
    "reviewer",
    "scout"
  ],
  "latest_event_id": 0,
  "now": 1783012334
};
