#!/usr/bin/env python3
"""Generate the auto-derived blocks of ``ARCHITECTURE.md``.

``ARCHITECTURE.md`` (repo root) is an orientation map for coding agents that
ties together backend, dashboard, and the Kanban dispatch lifecycle. The prose
sections are hand-maintained; the volatile lists (dashboard tabs, HTTP API
endpoints, Kanban DB schema, config keys) are generated from the live code by
this script and written *only* between ``<!-- BEGIN GENERATED:x -->`` /
``<!-- END GENERATED:x -->`` marker pairs.

Generation strategy (per source, robustest variant — see ARCHITECTURE.md plan):
  - api-endpoints : runtime-import the FastAPI ``app`` and iterate ``app.routes``
                    (captures statically-declared AND dynamically-mounted plugin
                    routes in one pass). Importing ``hermes_cli.web_server`` is
                    side-effect-free (~1s): ``_lifespan`` only runs under uvicorn
                    and the desktop ticker is gated behind ``HERMES_DESKTOP=1``.
                    ``HERMES_WEB_DIST`` is forced to a nonexistent path so the
                    import never depends on a built frontend.
                    Fallback if import ever becomes unsafe: AST-parse the
                    ``@router.*`` / ``@app.*`` decorators in web_server.py +
                    plugins/kanban/dashboard/plugin_api.py.
  - db-schema     : import ``kanban_db.SCHEMA_SQL`` (in-repo single source of
                    truth; no kanban.db file needed).
  - config-keys   : import ``config.DEFAULT_CONFIG`` (authoritative defaults).
  - dashboard-tabs: regex-parse the ``tabs`` array in ControlShell.tsx joined
                    with the ``de.tabs`` label map (keeps the whole generator in
                    Python — no ts-node).

Each generated parser HARD-ERRORS (exit != 0) if it finds zero items, so a
silent regression (e.g. a refactored tab array) is caught by the gate instead
of emitting an empty table.

Usage:
    python3 scripts/gen_architecture_doc.py           # regenerate + write
    python3 scripts/gen_architecture_doc.py --check    # exit !=0 if stale (gate)
"""

import argparse
import os
import re
import sys
from collections import defaultdict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

DOC_PATH = os.path.join(REPO_ROOT, "ARCHITECTURE.md")
CONTROL_SHELL = os.path.join(REPO_ROOT, "web", "src", "control", "components", "ControlShell.tsx")
DE_I18N = os.path.join(REPO_ROOT, "web", "src", "control", "i18n", "de.ts")

FOOTER = "<!-- generated by scripts/gen_architecture_doc.py — do not edit by hand -->"


# --------------------------------------------------------------------------- #
# Marker engine
# --------------------------------------------------------------------------- #
def replace_between_markers(text: str, name: str, body: str) -> str:
    """Replace the content between the BEGIN/END markers for ``name``.

    Only the inner region changes; everything else (hand prose) is preserved.
    A function replacement is used so backslashes in ``body`` are never treated
    as regex group references.
    """
    begin = f"<!-- BEGIN GENERATED:{name} -->"
    end = f"<!-- END GENERATED:{name} -->"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    replacement = f"{begin}\n{body.rstrip()}\n\n{FOOTER}\n{end}"
    new_text, n = pattern.subn(lambda _m: replacement, text)
    if n == 0:
        raise SystemExit(f"marker block '{name}' not found in {DOC_PATH}")
    return new_text


# --------------------------------------------------------------------------- #
# Generators
# --------------------------------------------------------------------------- #
def _api_prefix(path: str) -> str:
    """Group key for an endpoint path (segment-based)."""
    parts = [p for p in path.split("/") if p]
    if not parts:
        return "/"
    if parts[0] != "api":
        return "/" + parts[0]
    if len(parts) >= 3 and parts[1] == "plugins":
        return "/" + "/".join(parts[:3])  # e.g. /api/plugins/kanban
    if len(parts) >= 2:
        return "/" + "/".join(parts[:2])  # e.g. /api/sessions
    return "/api"


def gen_api_endpoints() -> str:
    os.environ.setdefault("HERMES_WEB_DIST", "/nonexistent")
    import fastapi.routing as routing
    from hermes_cli.web_server import app

    routes = [r for r in app.routes if isinstance(r, routing.APIRoute)]
    if not routes:
        raise SystemExit("api-endpoints: 0 APIRoutes found — refusing to emit empty block")

    groups: dict[str, list] = defaultdict(list)
    for r in routes:
        methods = ",".join(sorted(m for m in r.methods if m not in ("HEAD", "OPTIONS")))
        groups[_api_prefix(r.path)].append((methods, r.path, r.name or ""))

    out = [f"_{len(routes)} HTTP endpoints across {len(groups)} groups._", ""]
    for prefix in sorted(groups):
        rows = sorted(groups[prefix], key=lambda x: (x[1], x[0]))
        out.append(f"#### `{prefix}`")
        out.append("")
        out.append("| Methods | Path | Handler |")
        out.append("|---|---|---|")
        for methods, path, name in rows:
            out.append(f"| {methods} | `{path}` | `{name}` |")
        out.append("")
    return "\n".join(out)


def gen_db_schema() -> str:
    from hermes_cli.kanban_db import SCHEMA_SQL

    # Strip ``--`` line comments BEFORE splitting on ``;`` — SCHEMA_SQL contains
    # semicolons inside comment text (e.g. "crash; reset...") which would
    # otherwise tear a CREATE TABLE statement in half.
    cleaned = re.sub(r"--[^\n]*", "", SCHEMA_SQL)
    tables = []
    for stmt in cleaned.split(";"):
        m = re.search(r"CREATE TABLE(?:\s+IF NOT EXISTS)?\s+(\w+)\s*\((.*)\)", stmt, re.DOTALL | re.IGNORECASE)
        if not m:
            continue
        name, body = m.group(1), m.group(2)
        cols = []
        for line in body.splitlines():
            line = line.strip().rstrip(",")
            if not line:
                continue
            head = line.split()[0]
            if head.upper() in ("PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT"):
                continue
            cols.append(head)
        tables.append((name, cols))

    if not tables:
        raise SystemExit("db-schema: 0 tables parsed from SCHEMA_SQL — refusing to emit empty block")

    out = [f"_{len(tables)} tables. Source of truth: `hermes_cli/kanban_db.py` (`SCHEMA_SQL`)._", ""]
    out.append("| Table | Columns |")
    out.append("|---|---|")
    for name, cols in tables:
        out.append(f"| `{name}` | {', '.join(f'`{c}`' for c in cols)} |")
    out.append("")
    out.append("<details><summary>Raw <code>SCHEMA_SQL</code></summary>")
    out.append("")
    out.append("```sql")
    out.append(SCHEMA_SQL.strip())
    out.append("```")
    out.append("")
    out.append("</details>")
    return "\n".join(out)


def _repr_default(v) -> str:
    s = repr(v)
    if len(s) > 60:
        s = s[:57] + "..."
    return s


def gen_config_keys() -> str:
    from hermes_cli.config import DEFAULT_CONFIG

    rows = []

    def walk(d, prefix=""):
        for k, v in d.items():
            key = f"{prefix}{k}"
            if isinstance(v, dict) and v:
                walk(v, key + ".")
            else:
                rows.append((key, _repr_default(v), type(v).__name__))

    walk(DEFAULT_CONFIG)
    if not rows:
        raise SystemExit("config-keys: 0 keys walked from DEFAULT_CONFIG — refusing to emit empty block")

    out = [f"_{len(rows)} leaf keys. Source of truth: `hermes_cli/config.py` (`DEFAULT_CONFIG`)._", ""]
    out.append("| Key | Default | Type |")
    out.append("|---|---|---|")
    for key, default, typ in rows:
        out.append(f"| `{key}` | `{default}` | {typ} |")
    out.append("")
    return "\n".join(out)


def gen_tabs() -> str:
    with open(CONTROL_SHELL, encoding="utf-8") as f:
        shell = f.read()
    with open(DE_I18N, encoding="utf-8") as f:
        de = f.read()

    m = re.search(r"tabs:\s*\{([^}]*)\}", de)
    labels = dict(re.findall(r'(\w+):\s*"([^"]*)"', m.group(1))) if m else {}

    # Match each tab object in the `tabs` array. Requiring `label: de.tabs.X`
    # naturally excludes secondaryNav entries (which use string labels).
    pattern = re.compile(
        r'id:\s*"([^"]+)",\s*'
        r'label:\s*de\.tabs\.(\w+),\s*'
        r'mobileLabel:\s*(?:"[^"]*"|de\.tabs\.\w+),\s*'
        r'path:\s*"([^"]+)",\s*'
        r'icon:\s*(\w+)'
    )
    entries = pattern.findall(shell)
    if not entries:
        raise SystemExit("dashboard-tabs: 0 tabs parsed from ControlShell.tsx — refusing to emit empty block")

    out = [f"_{len(entries)} tabs. Source of truth: `web/src/control/components/ControlShell.tsx`._", ""]
    out.append("| id | Label (de) | Route | Icon |")
    out.append("|---|---|---|---|")
    for tab_id, label_key, path, icon in entries:
        label = labels.get(label_key, label_key)
        out.append(f"| `{tab_id}` | {label} | `{path}` | `{icon}` |")
    out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def build_blocks() -> dict:
    return {
        "dashboard-tabs": gen_tabs(),
        "api-endpoints": gen_api_endpoints(),
        "db-schema": gen_db_schema(),
        "config-keys": gen_config_keys(),
    }


def render(doc_text: str, blocks: dict) -> str:
    for name, body in blocks.items():
        doc_text = replace_between_markers(doc_text, name, body)
    return doc_text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit !=0 if the doc is stale (for the gate)")
    args = ap.parse_args()

    if not os.path.exists(DOC_PATH):
        sys.stderr.write(f"error: {DOC_PATH} does not exist\n")
        return 2

    with open(DOC_PATH, encoding="utf-8") as f:
        current = f.read()

    updated = render(current, build_blocks())

    if args.check:
        if updated != current:
            sys.stderr.write(
                "ARCHITECTURE.md is stale — generated blocks drifted from the code.\n"
                "Run: python3 scripts/gen_architecture_doc.py\n"
            )
            return 1
        print("ARCHITECTURE.md is up to date.")
        return 0

    if updated != current:
        with open(DOC_PATH, "w", encoding="utf-8") as f:
            f.write(updated)
        print("ARCHITECTURE.md updated.")
    else:
        print("ARCHITECTURE.md already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
